
--1.
UPDATE "PROFILES" P
SET "FIRST_NAME" = 'Kemmy', "LAST_NAME" = 'Matty'
FROM "ACCOUNTS" A
WHERE P."ACCOUNT_ID" = A."ID"
AND A."EMAIL" = 'kjpmantos@vauldex.com';


--2.
SELECT 
  EXTRACT(DAY FROM "ATTEMPTED_AT") AS "Day",
  EXTRACT(MONTH FROM "ATTEMPTED_AT") AS "Month",
  EXTRACT(YEAR FROM "ATTEMPTED_AT") AS "Year"
FROM "ACCOUNT_AUTH_HISTORIES";


--3.
SELECT "ACCOUNTS".*
FROM "ACCOUNTS" A
JOIN "PROFILES" P ON P."ACCOUNT_ID" = A."ID"
WHERE P."FIRST_NAME" LIKE 'Eji%' 
   OR P."LAST_NAME" LIKE 'Eji%';


--4.
UPDATE "PROFILES"
SET "GENDER" = '♂'
WHERE "FIRST_NAME" LIKE '%John%' 
   OR "LAST_NAME" LIKE '%John%';


--5.
SELECT *
FROM "ACCOUNTS"
WHERE "CREATED_AT" BETWEEN '2023-08-01' AND '2023-08-15 23:59:59';


--6.
SELECT COUNT(*)
FROM "ACCOUNTS"
WHERE "CREATED_AT" BETWEEN '2023-08-01' AND '2023-09-01 23:59:59';


--7.
SELECT *
FROM "PROFILES" P
WHERE EXISTS (
  SELECT 1
  AND A."EMAIL" = 'rejima@vauldex.com'
);


--8.
SELECT "ACCOUNTS".*
  FROM "ACCOUNTS" A
  WHERE A."ID" = P."ACCOUNT_ID"
FROM "ACCOUNTS"
JOIN (
  SELECT DISTINCT ON ("ACCOUNT_ID") "ACCOUNT_ID", "IS_SUCCESS"
  FROM "ACCOUNT_AUTH_HISTORIES"
  ORDER BY "ACCOUNT_ID", "ATTEMPTED_AT" DESC
) AS latest_auth ON latest_auth."ACCOUNT_ID" = "ACCOUNTS"."ID"
WHERE latest_auth."IS_SUCCESS" = true;


--9.
SELECT "ACCOUNT_ID", "FIRST_NAME", "LAST_NAME", "GENDER",
  CASE 
    WHEN "GENDER" = '♂' THEN 'Male'
    WHEN "GENDER" = '♀' THEN 'Female'
FROM "PROFILES"
WHERE "GENDER" IN ('♂', '♀');


