-- --- !Ups
CREATE TABLE "USER" (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE "POST" (
    ID BIGSERIAL PRIMARY KEY,
    POSTTEXT TEXT NOT NULL,
    ID_USER BIGINT NOT NULL REFERENCES "USER"(ID),
    IMGURL VARCHAR(255)
);

-- --- !Downs
DROP TABLE "POST";
DROP TABLE "USER";
